[package]
name = "graphtorio-game"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
egui = "0.31.1"
egui-snarl = "0.7.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
