[package]
name = "graphtorio"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui-snarl = "0.7.1"
graphtorio-game = { path = "game" }
zstd = "0.13.3"

[build-dependencies]
bincode = "2.0.1"
graphtorio-game = { path = "game" }
zstd = "0.13.3"